-- 유저 생성 및 권한 부여 (SYSTEM 계정)
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER INT_BOOKS IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO INT_BOOKS;
ALTER USER INT_BOOKS QUOTA UNLIMITED ON USERS;

-- 기존 테이블/시퀀스 삭제
DROP SEQUENCE BOARD_SEQ;
DROP TABLE BOARD;
DROP TABLE MEMBER;

-- 회원 테이블
CREATE TABLE MEMBER (
    MEMBER_ID   VARCHAR2(30)  PRIMARY KEY,       -- ID (PK)
    MEMBER_NAME VARCHAR2(100) NOT NULL,           -- 회원 이름
    MEMBER_PW   VARCHAR2(100) NOT NULL,           -- 비밀번호
    EMAIL       VARCHAR2(100) NOT NULL            -- 이메일
);

-- 리뷰 게시판 테이블
CREATE TABLE BOARD (
    BOARD_ID      NUMBER         PRIMARY KEY,     -- ID (PK)
    BOARD_TITLE   VARCHAR2(200)  NOT NULL,        -- 제목
    BOARD_NUM     NUMBER         UNIQUE NOT NULL, -- 고유번호
    MEMBER_ID   VARCHAR2(100)  NOT NULL,        -- 작성자 (FK - 회원 ID)
    CREATED_AT    DATE           DEFAULT SYSDATE NOT NULL, -- 작성일자
    BOARD_CONTENT VARCHAR2(4000) NOT NULL,        -- 작성내용
    READ_COUNT    NUMBER         DEFAULT 0 NOT NULL,       -- 조회수
    BOOK_TITLE    VARCHAR2(300)  NOT NULL,        -- 책 제목
    CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
);

SELECT * FROM MEMBER;
SELECT * FROM BOARD;

-- 시퀀스
CREATE SEQUENCE BOARD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;